version: '3.8'

services:
  # Drimbox
   frontend:
    image: drimbox-front:latest
    ports:
      - 4200:4200
      
   drimbox-conso:
    build:
      context: ../../Backend
    ports:
      - 8082:8081
    environment:
      DRIMBOX_MODE: conso

   viewer-ohif:
    image: viewer-ohif:latest
    ports:
      - 3000:80
    environment:
      - PUBLIC_URL=http://localhost:3000/viewer/