version: '3.8'

services:
  # Drimbox
   frontend:
    image: drimbox-front:latest
    ports:
      - 4200:4200
      
   drimbox-conso:
    build:
      context: ../../Backend
    ports:
      - 8082:8081
    environment:
      DRIMBOX_MODE: conso
