version: '3.9'

services:
  # Drimbox conso
  # Default address : http://localhost:8081

  drimbox-conso:
    build:
      context: ../..
    ports:
      - 8081:8081
    environment:
      DRIMBOX_MODE: conso
    networks: 
      drimbox_network:
        ipv4_address: 175.12.0.24
    # labels:
    #   com.docker-tc.enabled: 1
    #   com.docker-tc.limit: 1mbps

  # Drimbox source
  # Default address : http://localhost:8082
  drimbox-source:
    build:
      context: ../..
    ports:
      - 8082:8082
      - 8090:8090
    environment:
      DRIMBOX_MODE: source
      JAVA_OPTIONS: -Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Dquarkus.http.port=8082 -Dpacs.baseUrl=http://174.20.0.12:8080
    networks: 
      pacs_network:
        ipv4_address: 174.20.0.25
      drimbox_network:
        ipv4_address: 175.12.0.25
    # labels:
    #   com.docker-tc.enabled: 1
    #   com.docker-tc.network_drimbox_network.limit: 5mbps
    #   com.docker-tc.network_pacs_network.limit: 3mbps


  # Sample DCM4CHE
  # Default address : http://localhost:8012/dcm4chee-arc/ui2/
  dcm4chee-ldap:
      container_name: ldap
      image: dcm4che/slapd-dcm4chee:2.4.57-23.2
      networks:
        - pacs_network

  # DCM4CHEE uses this PostgreSQL database
  dcm4chee-postgres:
    container_name: pacspostgres
    image: dcm4che/postgres-dcm4chee:13.1-23
    logging:
      driver: json-file
      options:
        max-size: "10m"
    environment:
      POSTGRES_DB: pacsdb 
      POSTGRES_USER: pacs 
      POSTGRES_PASSWORD: pacs
    volumes:
      - dcm4chee-db-data:/var/lib/postgresql/data
    networks:
      - pacs_network

  # The main DCM4CHEE container
  dcm4chee-arc:
    image: dcm4che/dcm4chee-arc-psql:5.23.2
    env_file: docker-compose.env
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9990:9990"
      - "9993:9993"
      - "11112:11112"
      - "2762:2762"
      - "2575:2575"
      - "12575:12575"
    environment:
      POSTGRES_DB: pacsdb
      POSTGRES_USER: pacs
      POSTGRES_PASSWORD: pacs
      STORAGE_DIR: /storage/fs1
      POSTGRES_HOST: pacspostgres
      WILDFLY_CHOWN: /storage /opt/wildfly/standalone
      WILDFLY_WAIT_FOR: ldap:389 pacspostgres:5432
      JAVA_OPTS: -Xms256m -Xmx1024m -XX:MetaspaceSize=960M -XX:MaxMetaspaceSize=2560m -Djava.net.preferIPv4Stack=true
    depends_on:
      - dcm4chee-ldap
      - dcm4chee-postgres
    volumes:
      - dcm4chee-arc-wildfly:/opt/wildfly/standalone
      - dcm4chee-arc-storage:/storage
    networks:
      pacs_network:
        ipv4_address: 174.20.0.12


volumes:
  dcm4chee-db-data:
  dcm4chee-arc-wildfly:
  dcm4chee-arc-storage:

networks:
  pacs_network:
    driver: bridge
    ipam:
      config:
        - subnet: 174.20.0.0/24
  drimbox_network:
    driver: bridge
    ipam:
      config:
        - subnet: 175.12.0.0/24