version: '3.8'

services:
  # Drimbox
  # Default address : http://localhost:8082

  drimbox-source:
    build:
      context: ../..
    ports:
      - 8082:8082
      - 8090:8090
    environment:
      DRIMBOX_MODE: source
      JAVA_OPTIONS: "-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Dquarkus.http.port=8082 -Dpacs.baseUrl=http://174.20.0.12:8080 -Dquarkus.datasource.jdbc.url=jdbc:postgresql://174.20.0.14:5432/postgres"
    networks:
      pacs_network:
        ipv4_address: 174.20.0.13

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pswd
      POSTGRES_DB: postgres
    volumes:
      - drimbox-source-database:/var/lib/postgresql/data
    networks:
      pacs_network:
        ipv4_address: 174.20.0.14


  # Sample DCM4CHE
  # Default address : http://localhost:8012/dcm4chee-arc/ui2/
  dcm4chee-ldap:
      container_name: ldap
      image: dcm4che/slapd-dcm4chee:2.4.57-23.2
      networks:
        - pacs_network

  # DCM4CHEE uses this PostgreSQL database
  dcm4chee-postgres:
    container_name: pacspostgres
    image: dcm4che/postgres-dcm4chee:13.1-23
    logging:
      driver: json-file
      options:
        max-size: "10m"
    environment:
      POSTGRES_DB: pacsdb 
      POSTGRES_USER: pacs 
      POSTGRES_PASSWORD: pacs
    volumes:
      - dcm4chee-db-data:/var/lib/postgresql/data
    networks:
      - pacs_network

  # The main DCM4CHEE container
  dcm4chee-arc:
    image: dcm4che/dcm4chee-arc-psql:5.23.2
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9990:9990"
      - "9993:9993"
      - "11112:11112"
      - "2762:2762"
      - "2575:2575"
      - "12575:12575"
    environment:
      POSTGRES_DB: pacsdb
      POSTGRES_USER: pacs
      POSTGRES_PASSWORD: pacs
      STORAGE_DIR: /storage/fs1
      POSTGRES_HOST: pacspostgres
      WILDFLY_CHOWN: /storage /opt/wildfly/standalone
      WILDFLY_WAIT_FOR: ldap:389 pacspostgres:5432
      JAVA_OPTS: -Xms256m -Xmx1024m -XX:MetaspaceSize=960M -XX:MaxMetaspaceSize=2560m -Djava.net.preferIPv4Stack=true
    depends_on:
      - dcm4chee-ldap
      - dcm4chee-postgres
    volumes:
      - dcm4chee-arc-wildfly:/opt/wildfly/standalone
      - dcm4chee-arc-storage:/storage
    networks:
      pacs_network:
        ipv4_address: 174.20.0.12


volumes:
  dcm4chee-db-data:
  dcm4chee-arc-wildfly:
  dcm4chee-arc-storage:
  drimbox-source-database:

networks:
  pacs_network:
    driver: bridge
    ipam:
      config:
        - subnet: 174.20.0.0/24